# Generated by Django 6.1.1 on 2026-10-09 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_alter_rebalanceevent_execution_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='momentumscore',
            name='momentum_score',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='rebalanceevent',
            name='execution_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('In Progress', 'IN_PROGRESS'), ('COMPLETED', 'Completed'), ('Failed', 'FAILED')], default='PENDING', max_length=20),
        ),
    ]
